- name: Deploy apps
  hosts: all
  become: true
  tasks:
    - name: Copy docker-compose files
      copy:
        src: "{{ item }}"
        dest: /etc/docker
      with_items:
        - ../../docker/docker-compose.yml
        - ../../docker/docker-compose-logging.yml

    - name: Run docker-compose
      docker_compose:
        project_src: /etc/docker/
        files:
          - /etc/docker/docker-compose.yml
          - /etc/docker/docker-compose-logging.yml
