name: Destroy app on vm

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.8

      - name: Fill YC service account key.json file
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: 'echo "$YC_SERVICE_ACCOUNT_KEY" | base64 -d > key.json'
        working-directory: terraform

      - name: Fill terraform tfvars file
        env:
          YC_TFVARS: ${{ secrets.YC_TFVARS }}
        run: 'echo "$YC_TFVARS" | base64 -d > terraform.tfvars'
        working-directory: terraform

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: terraform

      - name: Terraform Destroy
        run: terraform destroy --auto-approve
        working-directory: terraform
