name: Terraform validate and tflint

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.8

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint stage
        run: tflint -f compact
